//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GW2_TP_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoughtItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoughtItems()
        {
            this.SoldItems = new HashSet<SoldItems>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public double Price_buy { get; set; }
        public double Price_sell_plan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoldItems> SoldItems { get; set; }
    }
}
